### PR TITLE
added gitsome to the awesome list

### PR DESCRIPTION
**Pull request by ellerbrock**

### CODE REVIEW

**Comment by coderyi** [comment]
thank you ，Do you know Chinese

**Comment by Fykec** [comment]
Great commit

**Comment by coderyi** [comment]
Fykec，我换电脑之后把我们的slack忘记了，我们slack的地址是什么啊

**Comment by ellerbrock** [comment]
thanks, i only understand a little bit, not really can speak or understand. but here i saw the awesome list and i could see the other app names so i knew where to put it. i stay in taiwan right now, where are u guys located?

**Comment by coderyi** [comment]
Taiwan is really a great place, they use traditional Chinese, I was in Beijing, using a simplified

**Pull request merged**
